version: 0.2

phases:
  install:
    runtime-versions:
      java: corretto11
      docker: 18
  pre_build:
    commands:
      - echo "Pre_build"
      - echo "Logging in to Amazon ECR"
      - $(aws ecr get-login  --no-include-email --region us-east-1)
  build:
    commands:
      - echo "Build"
      - echo "Entered build phase"
      - echo "Building Java application"
      - cd  RPM-API-gatway-auth
      - mvn -DskipTests clean package
      - docker build -t rpm-api-gatway-auth-repo .
      - docker tag rpm-api-gatway-auth-repo:latest 234825976347.dkr.ecr.us-east-2.amazonaws.com/rpm-api-gatway-auth-repo:latest
  post_build:
    commands:
      - echo "Post_build"
      - docker push 234825976347.dkr.ecr.us-east-2.amazonaws.com/rpm-api-gatway-auth-repo:latest
      - printf '[{"name":"rpm-api-gatway-auth-container","imageUri":"%s"}]' 234825976347.dkr.ecr.us-east-2.amazonaws.com/rpm-api-gatway-auth-repo:latest > taskdefinition.json
      - cat taskdefinition.json

artifacts:
  files:
      - RPM-API-gatway-auth/taskdefinition.json