jwt:
  get:
    token:
      uri: /authenticate
  secret: random-secret-123

server:
  error:
    include-stacktrace: never
  port: 8008

spring:
  application:
    name: authorization-service
  datasource:
    platform: h2
    url: jdbc:h2:mem:product_management    
    driver-class-name: org.h2.Driver
  h2:
    console:
      enabled: true


zuul:
  routes:
    product-services:
      path: /product/**
      service-id: product-service
      strip-prefix: false

    cart-services:
      path: /cart/**
      service-id: cart-service
      strip-prefix: false

eureka:
  instance:
    hostname: ${vcap.application.uris[0]:localhost}
    prefer-ip-address: true
    lease-renewal-interval-in-seconds: 10
    lease-expiration-duration-in-seconds: 20
  client:
    service-url:
      defaultZone: http://3.142.148.8:8761/eureka
           